loki:
  auth_enabled: false
  storage_config:
    filesystem:
      directory: /tmp/loki/
  ingester:
    chunk_encoding: snappy
  tracing:
    enabled: true
  querier:
    # Default is 4, if you have enough memory and CPU you can increase, reduce if OOMing
    max_concurrent: 4
  useTestSchema: true

minio:
  enabled: false


deploymentMode: SingleBinary
write:
  replicas: 0
read:
  replicas: 0
backend:
  replicas: 0
singleBinary:
  replicas: 1
  persistence:
    storageClass: microk8s-hostpath
loki:
  schemaConfig:
    configs:
      - from: "2024-04-01"
        store: tsdb
        object_store: filesystem
        schema: v13
        index:
          prefix: loki_index_
          period: 24h
  auth_enabled: "false"
  commonConfig:
    replication_factor: 1
  storage:
    type: 'filesystem'
  compactor:
    retention_enabled: true
    compaction_interval: 10m
    delete_request_store: filesystem
  query_scheduler:
    max_outstanding_requests_per_tenant: 4096
  frontend:
    max_outstanding_per_tenant: 4096
  # query_range:
  #   parallelise_shardable_queries: true
  limits_config:
    retention_period: 336h  # 2 weeks
    split_queries_by_interval: 15m
    max_query_series: 100000
    max_query_parallelism: 32