apiVersion: v2
name: ms-emails-grpc
description: This is a Helm chart for the ms-emails-gRPC service
type: application
version: 0.0.2
appVersion: "0.0.2"
dependencies:
  - name: ms-base
    version: 0.0.14
    repository: "https://www.codedesignplus.com/helm-charts/"