---
global:
  clusterDomain: 'cluster.local'
gateway:
  enabled: true
minio:
  enabled: false
storage:
  trace:
    backend: local
    local:
      path: /var/tempo/traces
traces:
  otlp:
    http:
      enabled: true
    grpc:
      enabled: true
distributor:
  config:
    log_received_spans:
      enabled: true
    log_discarded_spans:
      enabled: true