{{- if .Values.vault.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ms-base.name" . }}-vaultsecret
type: Opaque
data:
  token: {{ .Values.vault.token | b64enc | quote }}
{{- end -}}