{{- if and (.Values.vault.create) (not .Values.vault.server) }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ms-base.fullname" . }}-vaultserver
data:
  server: {{ .Values.vault.server }}
{{- end -}}