{{- if and (.Values.vault.create) (.Values.vault.server) }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-vaultserver
data:
  server: {{ .Values.vault.server }}
  solution: {{ .Values.vault.solution }}
{{- end -}}