apiVersion: v2
name: ms-users-worker
description: This is a Helm chart for the ms-users Worker service
type: application
version: 0.0.2
appVersion: "0.0.2"
dependencies:
  - name: ms-base
    version: 0.0.15
    repository: "https://www.codedesignplus.com/helm-charts/"