apiVersion: v2
name: ms-rbac-grpc
description: This is a Helm chart for the ms-rbac-gRPC service
type: application
version: 0.0.1
appVersion: "0.0.1"
dependencies:
  - name: ms-base
    version: 0.0.1
    repository: "https://www.codedesignplus.com/helm-charts/"