service:
  ports:
    - name: loki
      port: 3100        
      targetPort: 3100
    - name: prometheus
      port: 9090        
      targetPort: 9090
    - name: grafana
      port: 3000
      targetPort: 3000
    - name: vault
      port: 8200
      targetPort: 8200

replicaCount: 1
resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 256Mi