apiVersion: v2
name: ms-rbac
description: This is a Helm chart for the ms-rbac project.
type: application
version: v0.2.0
appVersion: v0.2.0
dependencies:
  - name: ms-base
    version: "v0.1.0-beta.30"
    repository: "https://www.codedesignplus.com/helm-charts/"