apiVersion: v2
name: ms-archetype-grpc
description: This is a Helm chart for the ms-archetype-gRPC service
type: application
version: v0.2.0-alpha.2
appVersion: v0.2.0-alpha.2
dependencies:
  - name: ms-base
    version: 0.0.1
    repository: "https://www.codedesignplus.com/helm-charts/"