apiVersion: v2
name: ms-archetype
description: This is a Helm chart for the ms-archetype-gRPC service
type: application
version: 0.0.1
appVersion: "0.0.1"
dependencies:
  - name: ms-base
    version: "v0.1.0-beta.30"
    repository: "https://www.codedesignplus.com/helm-charts/"