type: object
properties:
  replicaCount:
    type: integer
    minimum: 1
  image:
    type: object
    properties:
      repository:
        type: string
      pullPolicy:
        type: string
        enum:
          - Always
          - IfNotPresent
          - Never
      tag:
        type: string
  imagePullSecrets:
    type: array
    items:
      type: object
  nameOverride:
    type: string
  fullnameOverride:
    type: string
  serviceAccount:
    type: object
    properties:
      create:
        type: boolean
      automount:
        type: boolean
      annotations:
        type: object
        additionalProperties:
          type: string
      name:
        type: string
  podAnnotations:
    type: object
    additionalProperties:
      type: string
  podLabels:
    type: object
    additionalProperties:
      type: string
  podSecurityContext:
    type: object
  securityContext:
    type: object
  service:
    type: object
    properties:
      type:
        type: string
        enum:
          - ClusterIP
          - NodePort
          - LoadBalancer
      port:
        type: integer
  ingress:
    type: object
    properties:
      enabled:
        type: boolean
      className:
        type: string
      annotations:
        type: object
        additionalProperties:
          type: string
      hosts:
        type: array
        items:
          type: object
          properties:
            host:
              type: string
            paths:
              type: array
              items:
                type: object
                properties:
                  path:
                    type: string
                  pathType:
                    type: string
      tls:
        type: array
        items:
          type: object
          properties:
            secretName:
              type: string
            hosts:
              type: array
              items:
                type: string
  resources:
    type: object
  livenessProbe:
    type: object
    properties:
      httpGet:
        type: object
        properties:
          path:
            type: string
          port:
            type: string
  readinessProbe:
    type: object
    properties:
      httpGet:
        type: object
        properties:
          path:
            type: string
          port:
            type: string
  autoscaling:
    type: object
    properties:
      enabled:
        type: boolean
      minReplicas:
        type: integer
      maxReplicas:
        type: integer
      targetCPUUtilizationPercentage:
        type: integer
  volumes:
    type: array
    items:
      type: object
  volumeMounts:
    type: array
    items:
      type: object
  nodeSelector:
    type: object
    additionalProperties:
      type: string
  tolerations:
    type: array
    items:
      type: object
  affinity:
    type: object
  virtualService:
    type: object
    properties:
      create:
        type: boolean
      hosts:
        type: array
        items:
          type: string
      gateways:
        type: array
        items:
          type: string
      http:
        type: array
        items:
          type: object
          properties:
            route:
              type: array
              items:
                type: object
                properties:
                  destination:
                    type: object
                    properties:
                      host:
                        type: string
                      port:
                        type: object
                        properties:
                          number:
                            type: integer