mode: deployment

config:
  receivers:
    otlp:
      protocols:
        grpc:
          endpoint: 0.0.0.0:4317
        http:
          endpoint: 0.0.0.0:4318
    prometheus:
      config:
        scrape_configs:
        - job_name: otel-collector-metrics
          scrape_interval: 10s
          static_configs:
          - targets: ['localhost:8888']
        - job_name: 'loki'
          scrape_interval: 10s
          static_configs:
          - targets: ['loki-headless.monitoring:3100']
        - job_name: 'tempo'
          scrape_interval: 10s
          static_configs:
          - targets: ['tempo-server-query-frontend-discovery.monitoring:3100']

  exporters:
    debug:
      verbosity: detailed
    otlphttp/loki:
      endpoint: http://loki-headless.monitoring:3100/otlp
    otlp:
      endpoint: tempo-server-query-frontend-discovery.monitoring:5317 # Send to Tempo
      tls:
        insecure: true
    otlphttp/prometheus:
      endpoint: http://0.0.0.0:8889 
      
  service:
    pipelines:
      traces:
        receivers: [otlp]
        exporters: [otlp]
      
      logs:
        receivers: [otlp]
        exporters: [otlphttp/loki]

      metrics:
        receivers: [otlp, prometheus]
        exporters: [otlphttp/prometheus]